use crate::config::Config;
use crate::tty;

/// Builds the full `eval "$(rsreadline init bash)"` output: per-character
/// `bind -x` bindings that keep suggestions live as-you-type, Tab/Backspace
/// bindings, dynamic Up/Down rebinding between our suggestion-cycle handler
/// and bash's native history browsing, and a `PROMPT_COMMAND` hook that
/// clears the suggestion block before each new prompt.
pub fn generate(config: &Config) -> String {
    let exe_q = shell_single_quote(&current_exe_string());
    let clear_seq = dollar_quote(&tty::clear_sequence(config.max_suggestions));

    let mut lines: Vec<String> = Vec::new();

    lines.push("# Generated by `rsreadline init bash` — eval this in your .bashrc.".to_string());
    lines.push("_RSREADLINE_SEL=0".to_string());
    lines.push("_RSREADLINE_BUSY=0".to_string());
    lines.push(r#"bind '"\e[A": previous-history'"#.to_string());
    lines.push(r#"bind '"\e[B": next-history'"#.to_string());
    lines.push(String::new());

    // ------------------------------------------------------------------
    // Why this trap exists (read this before touching anything below):
    //
    // bash's `bind -x` can replace what a *key* does, but it cannot hook
    // "the line was just accepted and is about to run" — that event is
    // handled entirely inside bash's own accept-line/execute-command
    // machinery, which `bind -x` has no access to. Concretely: we deliberately
    // do NOT bind Enter (see the top-level design notes for why intercepting
    // Enter is a dead end — you cannot both intercept it AND still trigger
    // bash's real submission from a bind -x handler). That means the
    // suggestion block we drew below the cursor is still sitting on screen,
    // untouched, at the exact moment your command starts producing its own
    // output. If that output is shorter than the leftover suggestion text
    // was wide, the two visually merge — e.g. a real error message ending up
    // with garbage like "ve --" glued onto it, which is leftover suggestion
    // text nothing ever cleared.
    //
    // `PROMPT_COMMAND` (see __rsreadline_prompt_reset far below) cleans the
    // block up, but only runs before the *next* prompt — i.e. after your
    // command has already finished and had every chance to collide with the
    // stale text. We need something that fires in the gap *between* Enter
    // being accepted and your command's first line of real output.
    //
    // bash's `DEBUG` trap is that something: `trap CMD DEBUG` runs CMD
    // immediately before every simple command bash is about to execute —
    // including the one you just typed and hit Enter on. This is the same
    // primitive the community `bash-preexec` project builds "preexec" hooks
    // out of for other tools.
    //
    // The catch (verified empirically, not just from docs — see the plan/
    // commit history): the DEBUG trap ALSO fires before every command
    // *inside* our own bind -x handler functions (self-insert, backspace,
    // tab, up/down each run several internal commands apiece). If we clear
    // the block unconditionally on every DEBUG firing, we'd also clear it
    // repeatedly *while you're still typing*, before our own handler gets a
    // chance to redraw it — not corruption, but wasteful and a flicker risk.
    //
    // The fix is `_RSREADLINE_BUSY`: every one of our own bind -x entry
    // points (__rsreadline_insert/backspace/tab/up/down) sets it to 1 for
    // the duration of its own work and back to 0 when done. The preexec
    // handler below skips clearing whenever that flag is set, so it only
    // ever actually fires for commands bash runs on ITS OWN behalf — i.e.
    // your real, just-submitted command line — not for our internal
    // bookkeeping.
    //
    // One known, accepted imprecision: DEBUG fires before the very FIRST
    // statement of each handler too, at which point that handler hasn't set
    // the flag yet (it can't — that assignment IS the first statement). So
    // there's one spurious clear right at the start of handling each
    // keystroke. This is harmless: every handler's own final action is
    // always a fresh, correct redraw (via __rsreadline_update), which
    // overwrites that spurious clear within the same handler invocation,
    // faster than a terminal could ever visibly flicker. It's a real,
    // understood trade-off for keeping this guard a single flag instead of
    // a much more elaborate (and fragile) "is this command text one of ours"
    // pattern-matcher.
    // ------------------------------------------------------------------
    lines.push("# See the long comment above for why this function and the".to_string());
    lines.push("# `trap ... DEBUG` line below it exist.".to_string());
    lines.push("__rsreadline_preexec() {".to_string());
    lines.push("    # Skip while one of our own handlers is still running —".to_string());
    lines.push("    # it owns the block and will redraw it itself when done.".to_string());
    lines.push("    [[ \"$_RSREADLINE_BUSY\" == 1 ]] && return".to_string());
    lines.push(format!("    printf '%s' {clear_seq} > /dev/tty"));
    lines.push("}".to_string());
    lines.push("# Fires immediately before every command bash is about to run,".to_string());
    lines.push("# including your just-submitted command line — this is what lets".to_string());
    lines.push("# us clear the suggestion block before that command's own output".to_string());
    lines.push("# can collide with it. See the comment block above.".to_string());
    lines.push("trap __rsreadline_preexec DEBUG".to_string());
    lines.push(String::new());

    lines.push("__rsreadline_update() {".to_string());
    lines.push("    local direction=\"$1\" result sel count".to_string());
    lines.push(format!(
        "    result=$({exe_q} render \"$READLINE_LINE\" \"$READLINE_POINT\" \"$_RSREADLINE_SEL\" \"$direction\")"
    ));
    lines.push("    IFS=$'\\t' read -r sel count <<< \"$result\"".to_string());
    lines.push("    _RSREADLINE_SEL=\"${sel:-0}\"".to_string());
    lines.push("    if [[ \"${count:-0}\" -gt 0 ]]; then".to_string());
    lines.push(r#"        bind -x '"\e[A": __rsreadline_up'"#.to_string());
    lines.push(r#"        bind -x '"\e[B": __rsreadline_down'"#.to_string());
    lines.push("    else".to_string());
    lines.push(r#"        bind '"\e[A": previous-history'"#.to_string());
    lines.push(r#"        bind '"\e[B": next-history'"#.to_string());
    lines.push("    fi".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    // Every function below that's bound directly to a key (i.e. every one of
    // these five) wraps its whole body in _RSREADLINE_BUSY=1 / =0. That's the
    // guard __rsreadline_preexec checks above — see the comment block by
    // `trap ... DEBUG` for the full explanation. __rsreadline_update doesn't
    // need its own copy of this: it's only ever called from one of these five,
    // so the flag is already 1 for its whole duration.
    lines.push("__rsreadline_up() {".to_string());
    lines.push("    _RSREADLINE_BUSY=1".to_string());
    lines.push("    __rsreadline_update up".to_string());
    lines.push("    _RSREADLINE_BUSY=0".to_string());
    lines.push("}".to_string());
    lines.push("__rsreadline_down() {".to_string());
    lines.push("    _RSREADLINE_BUSY=1".to_string());
    lines.push("    __rsreadline_update down".to_string());
    lines.push("    _RSREADLINE_BUSY=0".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("__rsreadline_insert() {".to_string());
    lines.push("    _RSREADLINE_BUSY=1".to_string());
    lines.push("    local ch=\"$1\"".to_string());
    lines.push(
        "    READLINE_LINE=\"${READLINE_LINE:0:READLINE_POINT}${ch}${READLINE_LINE:READLINE_POINT}\""
            .to_string(),
    );
    lines.push("    READLINE_POINT=$((READLINE_POINT + 1))".to_string());
    lines.push("    __rsreadline_update none".to_string());
    lines.push("    _RSREADLINE_BUSY=0".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("__rsreadline_backspace() {".to_string());
    lines.push("    _RSREADLINE_BUSY=1".to_string());
    lines.push("    if ((READLINE_POINT > 0)); then".to_string());
    lines.push(
        "        READLINE_LINE=\"${READLINE_LINE:0:READLINE_POINT-1}${READLINE_LINE:READLINE_POINT}\""
            .to_string(),
    );
    lines.push("        READLINE_POINT=$((READLINE_POINT - 1))".to_string());
    lines.push("    fi".to_string());
    lines.push("    __rsreadline_update none".to_string());
    lines.push("    _RSREADLINE_BUSY=0".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("__rsreadline_tab() {".to_string());
    lines.push("    _RSREADLINE_BUSY=1".to_string());
    lines.push(format!(
        "    local result=$({exe_q} complete \"$READLINE_LINE\" \"$READLINE_POINT\" \"$_RSREADLINE_SEL\")"
    ));
    lines.push("    if [[ -n \"$result\" ]]; then".to_string());
    lines.push("        READLINE_LINE=\"$result\"".to_string());
    lines.push("        READLINE_POINT=${#READLINE_LINE}".to_string());
    lines.push("    fi".to_string());
    lines.push("    __rsreadline_update none".to_string());
    lines.push("    _RSREADLINE_BUSY=0".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push(r#"bind -x '"\t": __rsreadline_tab'"#.to_string());
    lines.push(r#"bind -x '"\C-?": __rsreadline_backspace'"#.to_string());
    lines.push(r#"bind -x '"\C-h": __rsreadline_backspace'"#.to_string());
    lines.push(String::new());

    for byte in PRINTABLE_ASCII_RANGE {
        lines.push(bind_line_for_char(byte as char));
    }
    lines.push(String::new());

    lines.push("__rsreadline_prompt_reset() {".to_string());
    lines.push(
        "    # Safety net: if some prior handler invocation didn't reach its own".to_string(),
    );
    lines.push("    # _RSREADLINE_BUSY=0 (e.g. the rsreadline binary errored or hung".to_string());
    lines.push("    # mid-call), don't let the preexec guard stay stuck off forever.".to_string());
    lines.push("    _RSREADLINE_BUSY=0".to_string());
    lines.push(format!("    printf '%s' {clear_seq} > /dev/tty"));
    lines.push("    _RSREADLINE_SEL=0".to_string());
    lines.push(r#"    bind '"\e[A": previous-history'"#.to_string());
    lines.push(r#"    bind '"\e[B": next-history'"#.to_string());
    lines.push("}".to_string());
    lines.push(
        "PROMPT_COMMAND=\"__rsreadline_prompt_reset${PROMPT_COMMAND:+; }$PROMPT_COMMAND\""
            .to_string(),
    );

    lines.join("\n") + "\n"
}

const PRINTABLE_ASCII_RANGE: std::ops::RangeInclusive<u8> = 0x20..=0x7e;

fn current_exe_string() -> String {
    std::env::current_exe()
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|_| "rsreadline".to_string())
}

/// Wraps `s` as a single-quoted POSIX shell literal, safe for any byte
/// content including embedded single quotes.
fn shell_single_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

/// Wraps `s` as a bash ANSI-C-quoted (`$'...'`) literal, escaping control
/// bytes we're known to emit (ESC, CR, LF) plus backslash/single-quote.
fn dollar_quote(s: &str) -> String {
    let mut out = String::from("$'");
    for b in s.bytes() {
        match b {
            b'\\' => out.push_str("\\\\"),
            b'\'' => out.push_str("\\'"),
            0x1b => out.push_str("\\033"),
            b'\r' => out.push_str("\\r"),
            b'\n' => out.push_str("\\n"),
            0x20..=0x7e => out.push(b as char),
            other => out.push_str(&format!("\\x{other:02x}")),
        }
    }
    out.push('\'');
    out
}

/// Escapes a character for use inside readline's own `"key": command`
/// key-sequence quoting (only `\` and `"` are special there).
fn readline_keyseq_escape(c: char) -> String {
    match c {
        '\\' => "\\\\".to_string(),
        '"' => "\\\"".to_string(),
        other => other.to_string(),
    }
}

fn bind_line_for_char(c: char) -> String {
    let key = readline_keyseq_escape(c);
    let command = format!("__rsreadline_insert {}", shell_single_quote(&c.to_string()));
    let combined = format!("\"{key}\": {command}");
    format!("bind -x {}", shell_single_quote(&combined))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::process::{Command, Stdio};

    fn default_config() -> Config {
        Config::parse("", None)
    }

    #[test]
    fn one_binding_per_printable_char_plus_special_keys() {
        let script = generate(&default_config());
        let char_bindings = script
            .lines()
            .filter(|l| l.starts_with("bind -x '\"") && l.contains("__rsreadline_insert"))
            .count();
        assert_eq!(char_bindings, 95); // 0x20..=0x7e inclusive

        assert!(script.contains(r#"bind -x '"\t": __rsreadline_tab'"#));
        assert!(script.contains(r#"bind -x '"\C-?": __rsreadline_backspace'"#));
        assert!(script.contains(r#"bind -x '"\C-h": __rsreadline_backspace'"#));
    }

    #[test]
    fn each_char_binding_is_distinct() {
        let script = generate(&default_config());
        let mut bindings: Vec<&str> = script
            .lines()
            .filter(|l| l.starts_with("bind -x '\"") && l.contains("__rsreadline_insert"))
            .collect();
        let before = bindings.len();
        bindings.sort_unstable();
        bindings.dedup();
        assert_eq!(bindings.len(), before);
    }

    #[test]
    fn special_shell_characters_are_escaped_safely() {
        for c in ['\'', '"', '\\', '`', '$', ' '] {
            let line = bind_line_for_char(c);
            // The whole "keyseq": command segment must be wrapped in a single
            // shell argument (starts right after "bind -x ").
            assert!(line.starts_with("bind -x '"));
            assert!(line.ends_with('\''));
        }
    }

    #[test]
    fn generated_script_is_valid_bash_syntax() {
        let script = generate(&default_config());
        let mut child = Command::new("bash")
            .arg("-n")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("bash must be available to run this test");
        child
            .stdin
            .take()
            .expect("stdin")
            .write_all(script.as_bytes())
            .expect("write script to bash -n");
        let output = child.wait_with_output().expect("bash -n exited");
        assert!(
            output.status.success(),
            "bash -n failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn shell_single_quote_handles_embedded_quotes() {
        assert_eq!(shell_single_quote("it's"), "'it'\\''s'");
    }

    #[test]
    fn dollar_quote_escapes_escape_byte() {
        let q = dollar_quote("\x1b[2K");
        assert_eq!(q, "$'\\033[2K'");
    }

    #[test]
    fn debug_trap_and_preexec_guard_are_wired_up() {
        let script = generate(&default_config());
        assert!(script.contains("_RSREADLINE_BUSY=0"), "initial declaration");
        assert!(script.contains("__rsreadline_preexec() {"));
        assert!(script.contains("trap __rsreadline_preexec DEBUG"));
        assert!(script.contains("[[ \"$_RSREADLINE_BUSY\" == 1 ]] && return"));
    }

    #[test]
    fn every_bind_x_entry_handler_sets_and_clears_the_busy_guard() {
        // Every function bound directly via `bind -x` (as opposed to
        // __rsreadline_update, which is only ever called from one of these)
        // must set _RSREADLINE_BUSY=1 as its first real action and reset it
        // to 0 before returning, so __rsreadline_preexec's guard check is
        // accurate for the whole duration of the handler — see the "Why this
        // trap exists" comment block in `generate`.
        let script = generate(&default_config());
        for func in [
            "__rsreadline_up",
            "__rsreadline_down",
            "__rsreadline_insert",
            "__rsreadline_backspace",
            "__rsreadline_tab",
        ] {
            let start = script
                .find(&format!("{func}() {{"))
                .unwrap_or_else(|| panic!("{func} not found in generated script"));
            let body_end = script[start..]
                .find("\n}")
                .unwrap_or_else(|| panic!("{func} has no closing brace"));
            let body = &script[start..start + body_end];
            assert!(
                body.contains("_RSREADLINE_BUSY=1"),
                "{func} must set the busy guard"
            );
            assert!(
                body.contains("_RSREADLINE_BUSY=0"),
                "{func} must clear the busy guard before returning"
            );
        }
    }

    #[test]
    fn prompt_reset_resets_the_busy_guard_as_a_safety_net() {
        let script = generate(&default_config());
        let start = script
            .find("__rsreadline_prompt_reset() {")
            .expect("prompt_reset not found");
        let body_end = script[start..]
            .find("\n}")
            .expect("prompt_reset has no closing brace");
        let body = &script[start..start + body_end];
        assert!(body.contains("_RSREADLINE_BUSY=0"));
    }
}
