use crate::config::Config;
use crate::tty;

/// Builds the full `eval "$(rsreadline init bash)"` output: per-character
/// `bind -x` bindings that keep suggestions live as-you-type, Tab/Backspace
/// bindings, dynamic Up/Down rebinding between our suggestion-cycle handler
/// and bash's native history browsing, and a `PROMPT_COMMAND` hook that
/// clears the suggestion block before each new prompt.
pub fn generate(config: &Config) -> String {
    let exe_q = shell_single_quote(&current_exe_string());
    let clear_seq = dollar_quote(&tty::clear_sequence(config.max_suggestions));

    let mut lines: Vec<String> = Vec::new();

    lines.push("# Generated by `rsreadline init bash` — eval this in your .bashrc.".to_string());
    lines.push("_RSREADLINE_SEL=0".to_string());
    lines.push(r#"bind '"\e[A": previous-history'"#.to_string());
    lines.push(r#"bind '"\e[B": next-history'"#.to_string());
    lines.push(String::new());

    lines.push("__rsreadline_update() {".to_string());
    lines.push("    local direction=\"$1\" result sel count".to_string());
    lines.push(format!(
        "    result=$({exe_q} render \"$READLINE_LINE\" \"$READLINE_POINT\" \"$_RSREADLINE_SEL\" \"$direction\")"
    ));
    lines.push("    IFS=$'\\t' read -r sel count <<< \"$result\"".to_string());
    lines.push("    _RSREADLINE_SEL=\"${sel:-0}\"".to_string());
    lines.push("    if [[ \"${count:-0}\" -gt 0 ]]; then".to_string());
    lines.push(r#"        bind -x '"\e[A": __rsreadline_up'"#.to_string());
    lines.push(r#"        bind -x '"\e[B": __rsreadline_down'"#.to_string());
    lines.push("    else".to_string());
    lines.push(r#"        bind '"\e[A": previous-history'"#.to_string());
    lines.push(r#"        bind '"\e[B": next-history'"#.to_string());
    lines.push("    fi".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("__rsreadline_up() { __rsreadline_update up; }".to_string());
    lines.push("__rsreadline_down() { __rsreadline_update down; }".to_string());
    lines.push(String::new());

    lines.push("__rsreadline_insert() {".to_string());
    lines.push("    local ch=\"$1\"".to_string());
    lines.push(
        "    READLINE_LINE=\"${READLINE_LINE:0:READLINE_POINT}${ch}${READLINE_LINE:READLINE_POINT}\""
            .to_string(),
    );
    lines.push("    READLINE_POINT=$((READLINE_POINT + 1))".to_string());
    lines.push("    __rsreadline_update none".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("__rsreadline_backspace() {".to_string());
    lines.push("    if ((READLINE_POINT > 0)); then".to_string());
    lines.push(
        "        READLINE_LINE=\"${READLINE_LINE:0:READLINE_POINT-1}${READLINE_LINE:READLINE_POINT}\""
            .to_string(),
    );
    lines.push("        READLINE_POINT=$((READLINE_POINT - 1))".to_string());
    lines.push("    fi".to_string());
    lines.push("    __rsreadline_update none".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("__rsreadline_tab() {".to_string());
    lines.push(format!(
        "    local result=$({exe_q} complete \"$READLINE_LINE\" \"$READLINE_POINT\" \"$_RSREADLINE_SEL\")"
    ));
    lines.push("    if [[ -n \"$result\" ]]; then".to_string());
    lines.push("        READLINE_LINE=\"$result\"".to_string());
    lines.push("        READLINE_POINT=${#READLINE_LINE}".to_string());
    lines.push("    fi".to_string());
    lines.push("    __rsreadline_update none".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push(r#"bind -x '"\t": __rsreadline_tab'"#.to_string());
    lines.push(r#"bind -x '"\C-?": __rsreadline_backspace'"#.to_string());
    lines.push(r#"bind -x '"\C-h": __rsreadline_backspace'"#.to_string());
    lines.push(String::new());

    for byte in PRINTABLE_ASCII_RANGE {
        lines.push(bind_line_for_char(byte as char));
    }
    lines.push(String::new());

    lines.push("__rsreadline_prompt_reset() {".to_string());
    lines.push(format!("    printf '%s' {clear_seq} > /dev/tty"));
    lines.push("    _RSREADLINE_SEL=0".to_string());
    lines.push(r#"    bind '"\e[A": previous-history'"#.to_string());
    lines.push(r#"    bind '"\e[B": next-history'"#.to_string());
    lines.push("}".to_string());
    lines.push(
        "PROMPT_COMMAND=\"__rsreadline_prompt_reset${PROMPT_COMMAND:+; }$PROMPT_COMMAND\""
            .to_string(),
    );

    lines.join("\n") + "\n"
}

const PRINTABLE_ASCII_RANGE: std::ops::RangeInclusive<u8> = 0x20..=0x7e;

fn current_exe_string() -> String {
    std::env::current_exe()
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|_| "rsreadline".to_string())
}

/// Wraps `s` as a single-quoted POSIX shell literal, safe for any byte
/// content including embedded single quotes.
fn shell_single_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

/// Wraps `s` as a bash ANSI-C-quoted (`$'...'`) literal, escaping control
/// bytes we're known to emit (ESC, CR, LF) plus backslash/single-quote.
fn dollar_quote(s: &str) -> String {
    let mut out = String::from("$'");
    for b in s.bytes() {
        match b {
            b'\\' => out.push_str("\\\\"),
            b'\'' => out.push_str("\\'"),
            0x1b => out.push_str("\\033"),
            b'\r' => out.push_str("\\r"),
            b'\n' => out.push_str("\\n"),
            0x20..=0x7e => out.push(b as char),
            other => out.push_str(&format!("\\x{other:02x}")),
        }
    }
    out.push('\'');
    out
}

/// Escapes a character for use inside readline's own `"key": command`
/// key-sequence quoting (only `\` and `"` are special there).
fn readline_keyseq_escape(c: char) -> String {
    match c {
        '\\' => "\\\\".to_string(),
        '"' => "\\\"".to_string(),
        other => other.to_string(),
    }
}

fn bind_line_for_char(c: char) -> String {
    let key = readline_keyseq_escape(c);
    let command = format!("__rsreadline_insert {}", shell_single_quote(&c.to_string()));
    let combined = format!("\"{key}\": {command}");
    format!("bind -x {}", shell_single_quote(&combined))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::process::{Command, Stdio};

    fn default_config() -> Config {
        Config::parse("", None)
    }

    #[test]
    fn one_binding_per_printable_char_plus_special_keys() {
        let script = generate(&default_config());
        let char_bindings = script
            .lines()
            .filter(|l| l.starts_with("bind -x '\"") && l.contains("__rsreadline_insert"))
            .count();
        assert_eq!(char_bindings, 95); // 0x20..=0x7e inclusive

        assert!(script.contains(r#"bind -x '"\t": __rsreadline_tab'"#));
        assert!(script.contains(r#"bind -x '"\C-?": __rsreadline_backspace'"#));
        assert!(script.contains(r#"bind -x '"\C-h": __rsreadline_backspace'"#));
    }

    #[test]
    fn each_char_binding_is_distinct() {
        let script = generate(&default_config());
        let mut bindings: Vec<&str> = script
            .lines()
            .filter(|l| l.starts_with("bind -x '\"") && l.contains("__rsreadline_insert"))
            .collect();
        let before = bindings.len();
        bindings.sort_unstable();
        bindings.dedup();
        assert_eq!(bindings.len(), before);
    }

    #[test]
    fn special_shell_characters_are_escaped_safely() {
        for c in ['\'', '"', '\\', '`', '$', ' '] {
            let line = bind_line_for_char(c);
            // The whole "keyseq": command segment must be wrapped in a single
            // shell argument (starts right after "bind -x ").
            assert!(line.starts_with("bind -x '"));
            assert!(line.ends_with('\''));
        }
    }

    #[test]
    fn generated_script_is_valid_bash_syntax() {
        let script = generate(&default_config());
        let mut child = Command::new("bash")
            .arg("-n")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("bash must be available to run this test");
        child
            .stdin
            .take()
            .expect("stdin")
            .write_all(script.as_bytes())
            .expect("write script to bash -n");
        let output = child.wait_with_output().expect("bash -n exited");
        assert!(
            output.status.success(),
            "bash -n failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn shell_single_quote_handles_embedded_quotes() {
        assert_eq!(shell_single_quote("it's"), "'it'\\''s'");
    }

    #[test]
    fn dollar_quote_escapes_escape_byte() {
        let q = dollar_quote("\x1b[2K");
        assert_eq!(q, "$'\\033[2K'");
    }
}
