//! Generates the bash glue script `rsreadline init bash` prints for
//! `.bashrc` to `eval`. Each piece of the script is built by its own
//! function below (`header`, `update_function`, the `bind -x` handlers,
//! ...) instead of one long list of `lines.push` calls, so the rationale
//! for a given piece of bash can sit as a doc comment directly above it.
//!
//! Key-sequence glossary, for the `bind`/`bind -x` strings below — this is
//! bash readline's own notation, not ours, and has to appear verbatim in
//! the generated script regardless of how it's named in this file:
//! - `\e[A` / `\e[B` — the escape sequences a terminal sends for the
//!   Up/Down arrow keys.
//! - `\C-i` — Ctrl-I, i.e. the Tab key.
//! - `\C-?` / `\C-h` — Ctrl-? (DEL, 0x7f) and Ctrl-H (BS, 0x08), the two
//!   different bytes a terminal can send for Backspace depending on
//!   settings; both are bound to the same handler.
//! - `\e[3;2~` — the sequence for Shift+Delete.

use crate::config::Config;
use crate::tty;

/// Builds the full `eval "$(rsreadline init bash)"` output: per-character
/// `bind -x` bindings that keep suggestions live as-you-type, a Backspace
/// binding, dynamic Up/Down rebinding between our suggestion-cycle handler
/// and bash's native history browsing, dynamic Tab rebinding between bash's
/// native completion and our no-op (once a suggestion is selected, Enter is
/// how it gets confirmed, not Tab), and a `PROMPT_COMMAND` hook that clears
/// the suggestion block before each new prompt.
pub fn generate(config: &Config) -> String {
    let exe_q = shell_single_quote(&current_exe_string());
    let clear_seq = dollar_quote(&tty::clear_sequence(config.max_suggestions));

    let mut out = String::new();
    out.push_str(header());
    out.push_str(&preexec_and_debug_trap(&clear_seq));
    out.push_str(&update_function(&exe_q));
    out.push_str(cycle_handlers());
    out.push_str(insert_handler());
    out.push_str(backspace_handler());
    out.push_str(tab_noop_handler());
    out.push_str(delete_selected_handler());
    out.push_str(static_bindings());
    out.push_str(&char_bindings());
    out.push_str(&prompt_reset(&clear_seq));
    out
}

/// Static setup emitted once at the top of the script: disables readline's
/// own re-binding of the terminal's erase key, declares the
/// selection/query/busy state variables, and points Up/Down/Tab at bash's
/// native behavior — the correct starting state, since nothing has been
/// typed yet and so no suggestions exist.
///
/// `bind-tty-special-chars off`: without it, readline continuously re-binds
/// whatever key `stty erase` points to (Backspace, almost always) back to
/// its own default, ignoring any `bind`/`bind -x` we issue for it —
/// confirmed with a real pty test, not just reasoned about
/// (`tests/backspace_refreshes_suggestions.rs`). Toggling `stty erase`
/// itself around each command also works, but was rejected: it's a
/// terminal-wide setting, and a failed restore could break Backspace in
/// *every* program running in that terminal, not just here.
///
/// `_RSREADLINE_SEL` empty means "nothing selected" — suggestions appear
/// unselected as you type; only Up/Down picks one. `_RSREADLINE_QUERY` is
/// what you actually typed, kept separate from `READLINE_LINE` because
/// Up/Down overwrites `READLINE_LINE` with a selection preview, and cycling
/// needs to keep matching against the real typed text, not that preview —
/// see `update_function`.
fn header() -> &'static str {
    r#"# Generated by `rsreadline init bash` — eval this in your .bashrc.
bind 'set bind-tty-special-chars off'
_RSREADLINE_SEL=""
_RSREADLINE_QUERY=""
_RSREADLINE_BUSY=0
bind '"\e[A": previous-history'
bind '"\e[B": next-history'
bind '"\C-i": complete'

"#
}

/// The `DEBUG` trap that clears the stale suggestion block before bash runs
/// a real command. Enter is never rebound — `bind -x` can't intercept a key
/// and still trigger bash's own `accept-line` — so without this, the block
/// would sit on screen untouched for as long as the submitted command runs
/// (`PROMPT_COMMAND`, in `prompt_reset`, only cleans up before the *next*
/// prompt), and short command output could end up with leftover suggestion
/// characters glued onto it.
///
/// bash's `DEBUG` trap runs immediately before every simple command bash
/// executes, including a just-submitted line (the same primitive
/// `bash-preexec` uses) — but also before commands *inside* our own
/// `bind -x` handlers. `_RSREADLINE_BUSY`, set around each handler's body
/// below, is what keeps this trap from clearing mid-handler: it only
/// actually clears when bash is running a real command. One accepted gap:
/// `DEBUG` fires before each handler's very first statement too, before the
/// flag is set — a harmless spurious clear, since that handler's own final
/// action always redraws correctly right after.
/// Regression test: `tests/enter_preexec_clears_stale_suggestions.rs`.
fn preexec_and_debug_trap(clear_seq: &str) -> String {
    let mut out = String::from(
        r#"# See ARCHITECTURE.md for why this function and the trap below it exist.
__rsreadline_preexec() {
    # Skip while one of our own handlers is still running —
    # it owns the block and will redraw it itself when done.
    [[ "$_RSREADLINE_BUSY" == 1 ]] && return
    printf '%s' "#,
    );
    out.push_str(clear_seq);
    out.push_str(" > /dev/tty\n}\ntrap __rsreadline_preexec DEBUG\n\n");
    out
}

/// The field separator for `render`'s response, shared by both sides of the
/// call: `main.rs::cmd_render` emits it between `selected`/`match_count`/
/// `fill_text`, and `read_result_line` below parses it back out via bash's
/// IFS-splitting `read` — into which `sel`/`fill` can legitimately arrive
/// empty (nothing selected / no fill).
///
/// Has to be `\x01` (SOH), not a tab or other whitespace: bash's `read`
/// treats IFS *whitespace* characters (space/tab/newline) as collapsible
/// even with a custom IFS, silently dropping empty fields anywhere but the
/// last — verified directly: `IFS=$'\t' read -r a b c <<< $'\t3\t'` gives
/// `a=3 b= c=`, not `a= b=3 c=`. Every field after the first empty one
/// shifts left, so `count` (which decides the Up/Down rebind just below)
/// would silently go missing. `\x01` isn't whitespace, so `read` splits on
/// it literally, and it can't plausibly appear in real command text the way
/// a stray tab or pipe might.
pub(crate) const FIELD_SEP: char = '\x01';

/// The `read` line in `update_function` that consumes `FIELD_SEP` — see its
/// doc comment for why it has to be this exact byte.
fn read_result_line() -> String {
    format!(
        "    IFS={} read -r sel count fill <<< \"$result\"\n",
        dollar_quote(&FIELD_SEP.to_string())
    )
}

/// The handler every key binding below eventually calls. `direction`
/// decides what `query`/`point` mean: for `none` (typing), the current
/// `READLINE_LINE` both becomes the query and is re-stored into
/// `_RSREADLINE_QUERY`; for anything else (cycling, tab-noop, delete), the
/// previously stored query is reused unchanged, so cycling always matches
/// against what was actually typed rather than whatever the last selection
/// preview left in `READLINE_LINE`.
///
/// After the call, Up/Down and Tab are dynamically re-pointed based on the
/// response: Up/Down go to our cycle handlers when there are matches to
/// cycle through, back to bash's native `previous-history`/`next-history`
/// otherwise; Tab goes to our no-op once something is selected (Enter is
/// how a selection gets confirmed, not Tab), back to bash's native
/// `complete` once the selection clears. `bind -x` can't intercept a key
/// and still fall through to its native action, so this rebind — not a
/// wrapper around the native function — is how both keys keep their normal
/// behavior in the states we don't want to touch.
/// Regression test: `tests/happy_path_selection_and_completion.rs`.
fn update_function(exe_q: &str) -> String {
    let mut out = String::from(
        r#"__rsreadline_update() {
    local direction="$1" query point result sel count fill
    if [[ "$direction" == none ]]; then
        _RSREADLINE_QUERY="$READLINE_LINE"
        query="$READLINE_LINE"
        point="$READLINE_POINT"
    else
        query="$_RSREADLINE_QUERY"
        point=${#_RSREADLINE_QUERY}
    fi
    result=$("#,
    );
    out.push_str(exe_q);
    out.push_str(" render \"$query\" \"$point\" \"$_RSREADLINE_SEL\" \"$direction\")\n");
    out.push_str(&read_result_line());
    out.push_str(
        r#"    _RSREADLINE_SEL="$sel"
    if [[ -n "$fill" ]]; then
        READLINE_LINE="$fill"
        READLINE_POINT=${#READLINE_LINE}
    fi
    if [[ "${count:-0}" -gt 0 ]]; then
        bind -x '"\e[A": __rsreadline_up'
        bind -x '"\e[B": __rsreadline_down'
    else
        bind '"\e[A": previous-history'
        bind '"\e[B": next-history'
    fi
    if [[ -n "$_RSREADLINE_SEL" ]]; then
        bind -x '"\C-i": __rsreadline_tab_noop'
    else
        bind '"\C-i": complete'
    fi
}

"#,
    );
    out
}

/// `bind -x` fully replaces a key's action, but the binding itself can be
/// changed at any time — so instead of reimplementing bash's history
/// browsing, Up/Down are just repointed by `update_function` between these
/// two handlers and bash's own `previous-history`/`next-history`, based on
/// whether there's anything to cycle through. More correct than a
/// file-based re-walk of history: this uses bash's actual in-memory
/// history, including commands not yet flushed to disk.
///
/// Every function below that's bound directly to a key via `bind -x` wraps
/// its whole body in `_RSREADLINE_BUSY=1` / `=0` — that's the guard
/// `preexec_and_debug_trap` checks. `update_function` doesn't need its own
/// copy: it's only ever called from one of these, so the flag is already 1
/// for its whole duration.
fn cycle_handlers() -> &'static str {
    r#"__rsreadline_up() {
    _RSREADLINE_BUSY=1
    __rsreadline_update up
    _RSREADLINE_BUSY=0
}
__rsreadline_down() {
    _RSREADLINE_BUSY=1
    __rsreadline_update down
    _RSREADLINE_BUSY=0
}

"#
}

/// Bound to every printable ASCII character (see `char_bindings`) — bash's
/// own default binding would insert the character itself, but that has to
/// be reimplemented here instead so every keystroke can also trigger
/// `update_function` and keep the suggestion block live.
fn insert_handler() -> &'static str {
    r#"__rsreadline_insert() {
    _RSREADLINE_BUSY=1
    local ch="$1"
    READLINE_LINE="${READLINE_LINE:0:READLINE_POINT}${ch}${READLINE_LINE:READLINE_POINT}"
    READLINE_POINT=$((READLINE_POINT + 1))
    __rsreadline_update none
    _RSREADLINE_BUSY=0
}

"#
}

/// Same reasoning as `insert_handler`: bash's default Backspace already
/// works, but it wouldn't refresh the suggestion block, so it's
/// reimplemented here to end in `update_function` too.
fn backspace_handler() -> &'static str {
    r#"__rsreadline_backspace() {
    _RSREADLINE_BUSY=1
    if ((READLINE_POINT > 0)); then
        READLINE_LINE="${READLINE_LINE:0:READLINE_POINT-1}${READLINE_LINE:READLINE_POINT}"
        READLINE_POINT=$((READLINE_POINT - 1))
    fi
    __rsreadline_update none
    _RSREADLINE_BUSY=0
}

"#
}

/// Only reachable while something is selected (see `update_function`'s
/// dynamic rebind) — Tab is meant to do nothing in that state. But "do
/// nothing" still needs a redraw (`"stay"`: keep the selection exactly as
/// it is) to repaint over the DEBUG-trap preexec hook's harmless spurious
/// clear, which fires before this function's very first statement, before
/// `_RSREADLINE_BUSY` is set — otherwise the block would visibly vanish
/// until the next real keystroke instead of just staying put.
fn tab_noop_handler() -> &'static str {
    r#"__rsreadline_tab_noop() {
    _RSREADLINE_BUSY=1
    __rsreadline_update stay
    _RSREADLINE_BUSY=0
}

"#
}

/// Unlike the handlers above, this one's binding is static (see
/// `static_bindings`), so it's reachable at any time, including with
/// nothing selected — hence the `else` branch, rather than assuming a
/// selection always exists. `READLINE_LINE`/`READLINE_POINT` are reset to
/// the typed query *before* calling `update_function`: `READLINE_LINE` is
/// still holding the about-to-be-deleted entry's preview text, and
/// `update_function` only overwrites it when the response's `fill` comes
/// back non-empty (i.e. something is still selected after the delete) — so
/// if the delete leaves nothing selected, this reset is what's actually
/// left in place. Not redundant with `update_function`'s own point
/// calculation (which always derives from `_RSREADLINE_QUERY` for a
/// non-`none` direction regardless): this `READLINE_POINT` is purely about
/// the visible cursor position in that no-selection-left fallback case.
/// Regression test: `tests/shift_delete_removes_selected_suggestion.rs`.
fn delete_selected_handler() -> &'static str {
    r#"__rsreadline_delete_selected() {
    _RSREADLINE_BUSY=1
    if [[ -n "$_RSREADLINE_SEL" ]]; then
        READLINE_LINE="$_RSREADLINE_QUERY"
        READLINE_POINT=${#READLINE_LINE}
        __rsreadline_update delete
    else
        __rsreadline_update stay
    fi
    _RSREADLINE_BUSY=0
}

"#
}

/// Backspace's two possible key codes, plus Shift+Delete for removing the
/// currently selected suggestion from history. `\e[3;2~` is the standard
/// xterm/most-terminal-emulators CSI sequence for Shift+Delete — confirmed
/// only against whatever bytes this repo's own pty test sends
/// (`tests/shift_delete_removes_selected_suggestion.rs`), not against every
/// real terminal a user might run this in. All three bindings are static,
/// unlike Up/Down/Tab: bash has no native binding for any of them that
/// needs to be dynamically restored.
fn static_bindings() -> &'static str {
    r#"bind -x '"\C-?": __rsreadline_backspace'
bind -x '"\C-h": __rsreadline_backspace'
bind -x '"\e[3;2~": __rsreadline_delete_selected'

"#
}

/// One `bind -x` per printable ASCII character (0x20..=0x7e), each routed
/// through `__rsreadline_insert` — see `insert_handler`.
fn char_bindings() -> String {
    let mut out = String::new();
    for byte in PRINTABLE_ASCII_RANGE {
        out.push_str(&bind_line_for_char(byte as char));
        out.push('\n');
    }
    out.push('\n');
    out
}

/// Runs via `PROMPT_COMMAND` before every new prompt: flushes bash's
/// in-memory history to `HISTFILE` (bash only appends on shell exit by
/// default, so without this, a command run earlier in the same session
/// wouldn't suggest itself when retyped — confirmed with a real pty test,
/// not just docs), clears the suggestion block left over from the previous
/// line, resets the selection/query state, and restores Up/Down/Tab to
/// bash's native behavior for the fresh prompt.
/// Regression test: `tests/prompt_reset_flushes_history_to_disk.rs`.
fn prompt_reset(clear_seq: &str) -> String {
    let mut out = String::from(
        r#"__rsreadline_prompt_reset() {
    history -a
    # Safety net: if some prior handler invocation didn't reach its own
    # _RSREADLINE_BUSY=0 (e.g. the rsreadline binary errored or hung
    # mid-call), don't let the preexec guard stay stuck off forever.
    _RSREADLINE_BUSY=0
    printf '%s' "#,
    );
    out.push_str(clear_seq);
    out.push_str(
        r#" > /dev/tty
    _RSREADLINE_SEL=""
    _RSREADLINE_QUERY=""
    bind '"\e[A": previous-history'
    bind '"\e[B": next-history'
    bind '"\C-i": complete'
}
PROMPT_COMMAND="__rsreadline_prompt_reset${PROMPT_COMMAND:+; }$PROMPT_COMMAND"
"#,
    );
    out
}

const PRINTABLE_ASCII_RANGE: std::ops::RangeInclusive<u8> = 0x20..=0x7e;

fn current_exe_string() -> String {
    std::env::current_exe()
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|_| "rsreadline".to_string())
}

/// Wraps `s` as a single-quoted POSIX shell literal, safe for any byte
/// content including embedded single quotes.
fn shell_single_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

/// Wraps `s` as a bash ANSI-C-quoted (`$'...'`) literal, escaping control
/// bytes we're known to emit (ESC, CR, LF) plus backslash/single-quote.
fn dollar_quote(s: &str) -> String {
    let mut out = String::from("$'");
    for b in s.bytes() {
        match b {
            b'\\' => out.push_str("\\\\"),
            b'\'' => out.push_str("\\'"),
            0x1b => out.push_str("\\033"),
            b'\r' => out.push_str("\\r"),
            b'\n' => out.push_str("\\n"),
            0x20..=0x7e => out.push(b as char),
            other => out.push_str(&format!("\\x{other:02x}")),
        }
    }
    out.push('\'');
    out
}

/// Escapes a character for use inside readline's own `"key": command`
/// key-sequence quoting (only `\` and `"` are special there).
fn readline_keyseq_escape(c: char) -> String {
    match c {
        '\\' => "\\\\".to_string(),
        '"' => "\\\"".to_string(),
        other => other.to_string(),
    }
}

fn bind_line_for_char(c: char) -> String {
    let key = readline_keyseq_escape(c);
    let command = format!("__rsreadline_insert {}", shell_single_quote(&c.to_string()));
    let combined = format!("\"{key}\": {command}");
    format!("bind -x {}", shell_single_quote(&combined))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::process::{Command, Stdio};

    fn default_config() -> Config {
        Config::parse("", None)
    }

    #[test]
    fn one_binding_per_printable_char_plus_special_keys() {
        let script = generate(&default_config());
        let char_bindings = script
            .lines()
            .filter(|l| l.starts_with("bind -x '\"") && l.contains("__rsreadline_insert"))
            .count();
        assert_eq!(char_bindings, 95); // 0x20..=0x7e inclusive

        assert!(script.contains(r#"bind -x '"\C-?": __rsreadline_backspace'"#));
        assert!(script.contains(r#"bind -x '"\C-h": __rsreadline_backspace'"#));
        assert!(script.contains(r#"bind -x '"\e[3;2~": __rsreadline_delete_selected'"#));
        // Tab starts bound to bash's own native completion, not us — see
        // tab_starts_and_resets_to_native_completion.
        assert!(script.contains(r#"bind '"\C-i": complete'"#));
    }

    #[test]
    fn each_char_binding_is_distinct() {
        let script = generate(&default_config());
        let mut bindings: Vec<&str> = script
            .lines()
            .filter(|l| l.starts_with("bind -x '\"") && l.contains("__rsreadline_insert"))
            .collect();
        let before = bindings.len();
        bindings.sort_unstable();
        bindings.dedup();
        assert_eq!(bindings.len(), before);
    }

    #[test]
    fn special_shell_characters_are_escaped_safely() {
        for c in ['\'', '"', '\\', '`', '$', ' '] {
            let line = bind_line_for_char(c);
            // The whole "keyseq": command segment must be wrapped in a single
            // shell argument (starts right after "bind -x ").
            assert!(line.starts_with("bind -x '"));
            assert!(line.ends_with('\''));
        }
    }

    #[test]
    fn generated_script_is_valid_bash_syntax() {
        let script = generate(&default_config());
        let mut child = Command::new("bash")
            .arg("-n")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("bash must be available to run this test");
        child
            .stdin
            .take()
            .expect("stdin")
            .write_all(script.as_bytes())
            .expect("write script to bash -n");
        let output = child.wait_with_output().expect("bash -n exited");
        assert!(
            output.status.success(),
            "bash -n failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn shell_single_quote_handles_embedded_quotes() {
        assert_eq!(shell_single_quote("it's"), "'it'\\''s'");
    }

    #[test]
    fn dollar_quote_escapes_escape_byte() {
        let q = dollar_quote("\x1b[2K");
        assert_eq!(q, "$'\\033[2K'");
    }

    #[test]
    fn bind_tty_special_chars_is_disabled() {
        // Otherwise readline keeps re-binding whatever key stty erase points
        // to (Backspace) back to its own default, ignoring our bind -x for
        // it — see ARCHITECTURE.md.
        let script = generate(&default_config());
        assert!(script.contains("bind 'set bind-tty-special-chars off'"));
    }

    #[test]
    fn tab_dynamically_rebinds_between_native_completion_and_noop() {
        let script = generate(&default_config());
        // Initial state (nothing selected): native completion.
        assert!(script.contains(r#"bind '"\C-i": complete'"#));
        // __rsreadline_update flips it based on _RSREADLINE_SEL.
        assert!(script.contains(r#"bind -x '"\C-i": __rsreadline_tab_noop'"#));
        assert!(script.contains("if [[ -n \"$_RSREADLINE_SEL\" ]]; then"));
        // prompt_reset resets it back to native for the next line too.
        let prompt_reset_start = script
            .find("__rsreadline_prompt_reset() {")
            .expect("prompt_reset not found");
        let body_end = script[prompt_reset_start..]
            .find("\n}")
            .expect("prompt_reset has no closing brace");
        assert!(
            script[prompt_reset_start..prompt_reset_start + body_end]
                .contains(r#"bind '"\C-i": complete'"#)
        );
    }

    #[test]
    fn debug_trap_and_preexec_guard_are_wired_up() {
        let script = generate(&default_config());
        assert!(script.contains("_RSREADLINE_BUSY=0"), "initial declaration");
        assert!(script.contains("__rsreadline_preexec() {"));
        assert!(script.contains("trap __rsreadline_preexec DEBUG"));
        assert!(script.contains("[[ \"$_RSREADLINE_BUSY\" == 1 ]] && return"));
    }

    #[test]
    fn every_bind_x_entry_handler_sets_and_clears_the_busy_guard() {
        // Every function bound directly via `bind -x` (as opposed to
        // __rsreadline_update, which is only ever called from one of these)
        // must set _RSREADLINE_BUSY=1 as its first real action and reset it
        // to 0 before returning, so __rsreadline_preexec's guard check is
        // accurate for the whole duration of the handler — see the "Why this
        // trap exists" comment block in `generate`.
        let script = generate(&default_config());
        for func in [
            "__rsreadline_up",
            "__rsreadline_down",
            "__rsreadline_insert",
            "__rsreadline_backspace",
            "__rsreadline_tab_noop",
            "__rsreadline_delete_selected",
        ] {
            let start = script
                .find(&format!("{func}() {{"))
                .unwrap_or_else(|| panic!("{func} not found in generated script"));
            let body_end = script[start..]
                .find("\n}")
                .unwrap_or_else(|| panic!("{func} has no closing brace"));
            let body = &script[start..start + body_end];
            assert!(
                body.contains("_RSREADLINE_BUSY=1"),
                "{func} must set the busy guard"
            );
            assert!(
                body.contains("_RSREADLINE_BUSY=0"),
                "{func} must clear the busy guard before returning"
            );
        }
    }

    #[test]
    fn delete_selected_handler_has_both_branches() {
        let script = generate(&default_config());
        let start = script
            .find("__rsreadline_delete_selected() {")
            .expect("__rsreadline_delete_selected not found");
        let body_end = script[start..]
            .find("\n}")
            .expect("__rsreadline_delete_selected has no closing brace");
        let body = &script[start..start + body_end];

        // Something selected: reset the line to the typed query, then
        // delete — see the doc comment above the function in `generate`
        // for why the reset has to happen before this call.
        assert!(body.contains("READLINE_LINE=\"$_RSREADLINE_QUERY\""));
        assert!(body.contains("READLINE_POINT=${#READLINE_LINE}"));
        assert!(body.contains("__rsreadline_update delete"));
        // Nothing selected: this binding is static (always reachable), so
        // it still must redraw to repaint the DEBUG-trap's spurious clear.
        assert!(body.contains("__rsreadline_update stay"));
    }

    #[test]
    fn prompt_reset_resets_the_busy_guard_as_a_safety_net() {
        let script = generate(&default_config());
        let start = script
            .find("__rsreadline_prompt_reset() {")
            .expect("prompt_reset not found");
        let body_end = script[start..]
            .find("\n}")
            .expect("prompt_reset has no closing brace");
        let body = &script[start..start + body_end];
        assert!(body.contains("_RSREADLINE_BUSY=0"));
    }
}
